resources:
- metrics-deployment.yaml
- metrics-service.yaml
- metrics-servicemonitor.yaml
- metrics-prometheus-rules.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: metrics-server
  newName: quay.io/openshift_sandboxed_containers/openshift-sandboxed-containers-operator
  newTag: v1.9.0
