apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: operator-metrics-server
  name: operator-metrics-service
spec:
  ports:
  - port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: operator-metrics-server
status:
  loadBalancer: {}
