apiVersion: v1
kind: Secret
metadata:
  name: ocp-libvirt-secret
  namespace: openshift-sandboxed-containers-operator
type: Opaque
data:
#   lparip: ""
#   lparuser: ""
#   lparpswd: ""
stringData:
#   libvirtpool: "test-pool"
#   libvirvolume: "test-vol"
#   libvirtpooldirectory: "test-dir"
#   REDHAT_OFFLINE_TOKEN: " "
#   HOST_KEY_CERTS: "-----BEGIN CERTIFICATE-----

#     -----END CERTIFICATE-----"
